services:
  flask-backend:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  streamlit-frontend:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - flask-backend
    volumes:
      - .:/app
