DIABETES_INDICATORS_DATASET = "hf://datasets/Bena345/cdc-diabetes-health-indicators/"
DIABETES_INDICATORS_TARGET = "Diabetes_binary"
DIABETES_INDICATORS_TARGET_TYPE = "nominal"

DIABETES_PREDICTION_DATASET = "hf://datasets/marianeft/diabetes_prediction_dataset/"
DIABETES_PREDICTION_TARGET = "diabetes"
DIABETES_PREDICTION_TARGET_TYPE = "nominal"

DEFAULT_NUMERIC_IMPUTER_STRATEGY = "median"
DEFAULT_CATEGORY_IMPUTER_STRATEGY = "most_frequent"


RANDOM_FOREST_INDICATORS_MAX_DEPTH = 10
RANDOM_FOREST_INDICATORS_N_ESTIMATORS = 100
RANDOM_FOREST_INDICATORS_MIN_SAMPLES_SPLIT = 10

RANDOM_FOREST_PREDICTION_MAX_DEPTH = 10
RANDOM_FOREST_PREDICTION_N_ESTIMATORS = 100
RANDOM_FOREST_PREDICTION_MIN_SAMPLES_SPLIT = 10

KNN_INDICATORS_NEIGHBORS = 5
KNN_INDICATORS_THRESH = 0.2

KNN_PREDICTION_NEIGHBORS = 5
KNN_PREDICTION_THRESH = 0.2
